server:
  port: 8080
spring:
  application:
    name: user service

  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:8080/oauth2/callback/google"

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        transaction: DEBUG

